"""Adds defaults equals to zero to thumbs votes

Revision ID: 6794f45b63ce
Revises: d75cd8e4acbd
Create Date: 2019-08-20 08:42:52.685205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6794f45b63ce'
down_revision = 'd75cd8e4acbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
