"""Adds score field to Theme model, with default equals to 0

Revision ID: b1160f3890c6
Revises: 6794f45b63ce
Create Date: 2019-08-20 09:47:32.089956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1160f3890c6'
down_revision = '6794f45b63ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('themes', sa.Column('score', sa.Numeric(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('themes', 'score')
    # ### end Alembic commands ###
