"""Adds fields to Video model

Revision ID: d75cd8e4acbd
Revises: 2fc3dbd78c93
Create Date: 2019-08-20 07:45:59.888460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd75cd8e4acbd'
down_revision = '2fc3dbd78c93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('thumbs_down', sa.Integer(), nullable=True))
    op.add_column('videos', sa.Column('thumbs_up', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'thumbs_up')
    op.drop_column('videos', 'thumbs_down')
    # ### end Alembic commands ###
