"""Adds videos relationship to Theme model

Revision ID: e212536385c3
Revises: f107312c71be
Create Date: 2019-08-20 10:41:37.149196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e212536385c3'
down_revision = 'f107312c71be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
