"""Changes score field from Numeric to Float

Revision ID: f107312c71be
Revises: b1160f3890c6
Create Date: 2019-08-20 10:06:39.181773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f107312c71be'
down_revision = 'b1160f3890c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
